SodaCost                   1    # Manufacturer Suggested Retail Price (MSRP) per bottle
NumStudents                4    # number of students to create
MaxPurchases              10    # maximum number of bottles a student purchases
NumVendingMachines         3    # number of vending machines
MaxStockPerFlavour         5    # maximum number of bottles of each flavour in a vending machine
MaxShippedPerFlavour       6    # maximum number of bottles of each flavour generated by the bottling
                                #    plant per production run
TimeBetweenShipments       5    # length of time between shipment pickup
ParentalDelay             20    # length of time between new deposits of funds
NumCouriers                3    # maximum number of couriers in the pool


struct ConfigParms {
    unsigned int sodaCost;                      // MSRP per bottle
    unsigned int numStudents;                   // number of students to create
    unsigned int maxPurchases;                  // maximum number of bottles a student purchases
    unsigned int numVendingMachines;            // number of vending machines
    unsigned int maxStockPerFlavour;            // maximum number of bottles of each flavour stocked
    unsigned int maxShippedPerFlavour;          // number of bottles of each flavour in a shipment
    unsigned int timeBetweenShipments;          // length of time between shipment pickup
    unsigned int parentalDelay;                 // length of time between cash deposits
    unsigned int numCouriers;                   // number of couriers in the pool
};

void processConfigFile( const char *configFile, ConfigParms &cparms );



